agenda.titulo.pagina.consulta=Agendas Cadastradas
agenda.titulo.pagina.cadastro=Cadastro de Agenda
agenda.titulo.relatorio=Relatório de Compromissos por Período
agenda.label.nome=Nome:
agenda.label.periodo=Período:
agenda.botao.nova=Nova Agenda
agenda.botao.relatorio=Relatório
agenda.tabela.id=ID
agenda.tabela.nome=Nome da Agenda
agenda.tabela.periodo=Período
agenda.tabela.acoes=Ações