agenda.titulo.pagina.consulta=Agendas Cadastradas
agenda.titulo.pagina.cadastro=Cadastro de Agenda
agenda.titulo.relatorio=Relat\u00F3rio de Compromissos por Per\u00EDodo
agenda.label.nome=Nome:
agenda.label.periodo=Per\u00EDodo:
agenda.botao.nova=Nova Agenda
agenda.botao.relatorio=Relat\u00F3rio
agenda.tabela.id=ID
agenda.tabela.nome=Nome da Agenda
agenda.tabela.periodo=Per\u00EDodo
agenda.tabela.acoes=A\u00E7\u00F5es